=encoding utf8

=head1 NAME

impress.js --Automatic layout based on content structure--

=head1 DESCRIPTION

 <div id="impress" class="impress-not-supported">
 <section>
     <h1>Future Perfect</h1>
     ......
     <section> 
         <h1>Hypertext</h1>
         ......
     </section>
 
     <section> 
         <h1>Why a World Wide Web?</h1>  
         ......
     </section>
     ......
 </section>
 </div>

=head1 DEMO

http://yoshimurayuu.github.com/impress.js/test.html

=head1 BROWSER SUPPORT

It works on Chrome.
